
server:
  port: 8089

spring:
  security:
    user:
      name: sxadmin
      password: 123

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.100.84:1433;database=FSDBSS
    druid:
      username: sxsrv
      password:
      max-active: 100
    sql-script-encoding: gbk


logging:
  level:
    cn.gsq.queryform.dao: debug

